### ISSUE TITLE
Deposit's DSN reused and counterfeit bug

### ISSUE THREAD

**Issue by EuroHsu** [BOLT-Protocol/gringotts#12]
After user send ETH or token to contract for getting a DSN, user can reproduce many lightTxs with the same or wrong DSN so that he/she will obtain illegal balance.

1. Check the DSN is already used.
2. Check the DSN is mapping user address.

**Comment by BenjaminLu** [comment]
fixes #14

**Comment by EuroHsu** [comment]
DepositLog structure change leads to incorrect recognition result
